# Generated by Django 5.2.1 on 2025-06-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in attesa', 'In Attesa'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='in_attesa', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienti.cliente')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
            ],
        ),
    ]
