# Generated by Django 5.2.1 on 2025-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='quantita_disponibile',
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti/'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
